name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image with a timestamp tag
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:$(date +%s)

      # Step 4: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:$(date +%s)

      # step5: debug 
      - name: Display npm debug logs
        if: failure()
        run: cat /home/runner/.npm/_logs/*.log

      - name: Show Docker credentials (for debugging)
        run: |
          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"

        

          
