name: Build, SonarQube Scan, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v4

      # Show Docker credentials for debugging
      - name: Show Docker credentials (for debugging)
        run: |
          echo "Docker Username: ${{ secrets.DOCKER_USERNAME }}"

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Setup SonarQube Scanner
      - name: Set up SonarQube Scanner
        uses: SonarSource/sonarcloud-action@v2
        with:
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}

      # Step 4: SonarQube Analysis
      - name: Run SonarQube Scan
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)  # Get the short commit hash
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:$COMMIT_ID"
          echo "Running SonarQube Scan"
          sonar-scanner \
            -Dsonar.projectKey=nodejs-hello-world-test \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Step 5: Build Docker Image with Commit ID as tag
      - name: Build Docker image
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)  # Get the short commit hash
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:$COMMIT_ID"
          echo "Building Docker image with tag: $IMAGE_TAG"
          docker build . --file Dockerfile --tag $IMAGE_TAG

      # Debugging: List Docker images
      - name: List Docker images
        run: |
          docker images

      # Step 6: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          COMMIT_ID=$(git rev-parse --short HEAD)  # Get the short commit hash
          IMAGE_TAG="${{ secrets.DOCKER_USERNAME }}/nodejs-hello-world:$COMMIT_ID"
          echo "Pushing Docker image with tag: $IMAGE_TAG"
          docker push $IMAGE_TAG
